name       : lensfun
version    : 0.3.1
release    : 1
source     :
    - http://internode.dl.sourceforge.net/project/lensfun/0.3.1/lensfun-0.3.1.tar.gz : 216c23754212e051c8b834437e46af3812533bd770c09714e8c06c9d91cdb535
license    :
    - GPL-3.0
    - LGPL-3.0
    - CC-BY-SA-3.0
summary    : Library to correct optical lens defects and lens database
description: |
    Library to correct optical lens defects and lens database
builddeps  :
setup      : |
    %cmake .
build      : |
    %make
install    : |
    %make_install
