name       : lensfun
version    : 0.3.2
release    : 6
source     :
    - https://jztkft.dl.sourceforge.net/project/lensfun/0.3.2/lensfun-0.3.2.tar.gz : ae8bcad46614ca47f5bda65b00af4a257a9564a61725df9c74cb260da544d331
license    :
    - GPL-3.0-or-later
    - LGPL-3.0-or-later
    - CC-BY-SA-3.0
component  : multimedia.library
summary    : Library to correct optical lens defects and lens database
description: |
    Library to correct optical lens defects and lens database
setup      : |
    %patch -p1 < $pkgfiles/install-python-files.patch
    %patch -p1 < $pkgfiles/fix-memory-leak.patch
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
    install -Dm00644 $pkgfiles/lensfun.tmpfiles $installdir/usr/lib/tmpfiles.d/lensfun.conf
    rm $installdir/usr/bin/g-lensfun*
